/**
 * OzonFlow · 需求地图数据（与 REQUIREMENTS_MAP.md 同源，由 tools/build-requirements-md.js 生成文档）
 * status: live 已上线（现有视图/Agent 已实现） · partial 部分上线（现有模块部分覆盖） · planned 规划（尚未实现）
 * view: 已有视图 id，或规划中的目标视图（planned 行）
 * inferred: true = 痛点/做法为推断，未找到直接公开证据
 */
(typeof window !== 'undefined' ? window : globalThis).OzonFlowRequirements = (function () {
  const EV = {
    rfbsApi: 'https://salacoste.github.io/ozon-daytona-seller-api/daytona-ozon-api-docs/categories/15-delivery-rfbs.html',
    shipV4: 'https://github.com/gam6itko/ozon-seller/issues/83',
    ozonDocs: 'https://docs.ozon.ru/api/seller/',
    qualityCn: 'https://www.chwang.com/guide/485564690433',
    qualityCif: 'https://www.cifnews.com/guide/ozon/va9potyu',
    lateShip: 'https://m.amz123.com/guide/ozon/6friSeCb',
    onTime: 'https://www.cifnews.com/guide/ozon/aekrgwhj',
    apr2026: 'https://www.chwang.com/news/204428920697',
    errIndex: 'https://selsup.ru/blog/ozon-indeks-oshibok/',
    errIndex2: 'https://sell-profit.ru/indeks-oshibok-ozon',
    dxmGuide: 'https://help.dianxiaomi.com/guide/2189',
    dxmProfit: 'https://help.dianxiaomi.com/article/financialManagement/3394',
    dxmListing: 'https://help.dianxiaomi.com/article/productManagement/2376',
    dxmPlugin: 'https://www.dianxiaomi.com/blog/article/91',
    dxmTitle: 'https://www.dianxiaomi.com/blog/article/282',
    vat1: 'https://info.sibnet.ru/article/amp/702087/',
    vat2: 'https://retail-life.ru/transgranichnaja-onlajn-torgovlja-minfin-predlozhil-vvesti-nds-22-srazu/',
    vat3: 'https://deliver-2.com/news/marketplaces/vat-on-imports-via-marketplaces-7-from-2027-22-by-2029/',
    perf1: 'https://iseller.pro/instrukcii/performance-api-ozon',
    perf2: 'https://api-master.ru/ozon-api-blog/fetching-ads-campaigns-from-ozon-api',
    perfDocs: 'https://github.com/dragonsigh/ozon-performance-api-docs',
    contentRating: 'https://www.amz123.com/guide/ozon/3Fbky1gB',
    attrs: 'https://obliqapp.ru/blog/ru/harakteristiki-tovara-ozon-zapolnit-pravilno',
    imgSpec: 'https://obliqapp.ru/blog/ru/razmer-kartochki-ozon',
    aiImg: 'https://fotofactor.ru/blog/marketplace-requirements',
    aiImgOzon: 'https://guruseller.ru/ai-foto-dlya-kartochki-pryamo-v-kabinete-ozon-kak-rabotaet-vstroennaya-nejroset-i-kogda-ona-ne-pomozhet/',
    eac: 'https://www.gost-smk.com/info-4869.html',
    marking: 'https://www.10100.com/article/150013396',
    prohibited: 'https://www.10100.com/article/149218858',
    priceIndex: 'https://www.amz123.com/guide/ozon/OMdWQQih',
    followSell: 'https://erp.91miaoshou.com/blog/article_1354.html',
    priceIndex2: 'https://erp.91miaoshou.com/blog/article_1236.html',
    finApi: 'https://selsup.ru/blog/ozon-api-finance-2026/',
    finApiHabr: 'https://habr.com/ru/articles/1086658/',
    mpstats: 'https://mpstats.io/instruments/ozon/analytics',
    mpstatsCab: 'https://wiki.mpstats.io/ru/%D0%9A%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82_Ozon/%D0%A1%D0%B2%D0%BE%D0%B4%D0%BA%D0%B0',
    mpVsMg: 'https://mpria.ru/sravnenie-mpstats-vs-marketguru-bitva-titanov-analitiki-marketpleysov/',
    payout: 'https://kuakuakua.com/guides/ozon-payouts.html',
    payout2: 'https://www.amz123.com/guide/ozon/ws1QWbeL',
    currency: 'https://m.cifnews.com/guide/ozon/wtpym9y',
    actionsApi: 'https://www.postman.com/googlesheets/ozon-seller-api/request/5ak869i/',
    reviewApi: 'https://salacoste.github.io/ozon-daytona-seller-api/daytona-ozon-api-docs/categories/08-review.html',
    chatApi: 'https://salacoste.github.io/ozon-daytona-seller-api/daytona-ozon-api-docs/categories/13-chat.html',
    fulfillChoose: 'https://kuakuakua.com/guides/ozon-choose-fulfillment.html',
    fulfillCmp: 'https://ozon123.com/ozon-fbo-vs-fbs-shipping-guide/',
    logisticsChoose: 'https://kuakuakua.com/guides/ozon-choose-logistics.html',
    returnsIml: 'https://www.amz123.com/guide/ozongolbal/pGoJTfME',
    returnsPvz: 'https://www.amz123.com/guide/ozon/sW9gJUGL',
    commJul: 'https://www.chwe.cn/article/ZgTgKJIkXrc',
    commJul2: 'https://www.816kf.com/company/251.html',
    commAug: 'https://ozon123.com/ozon-fee-change-august-28/',
    storesLicense: 'https://kuakuakua.com/guides/ozon-stores-per-license.html',
    banGuide: 'https://erp.91miaoshou.com/blog/article_1950.html',
    suspicious: 'https://www.htqfw.com/article/139367',
    open1688: 'https://open.1688.com/',
    cardMerge: 'https://onefill.ru/news/ozon-navyol-poryadok-v-kartochkakh-tovarov-i-pochti-ne-vzyal-za-eto-deneg/',
    coreApi: 'https://github.com/a-ulianov/ozonapi',
    importHabr: 'https://habr.com/ru/articles/872228/',
    miaoshouAi: 'https://erp.91miaoshou.com/help_center/article_14152.html',
    miaoshouPrice: 'https://erp.91miaoshou.com/blog/article_4672.html',
    customs: 'https://global.lianlianpay.com/article/MTQyODcyLGJhNg.html',
    rfbsFees: 'https://www.chwang.com/guide/186994874026',
    dailySummary: 'https://selsup.ru/blog/ozon-ezhednevnaya-svodka/',
    mcp1: 'https://github.com/DeviceIngineering/ozon-mcp-server',
    mcp2: 'https://github.com/Oxonomy/ozon-seller-mcp',
  };

  const VERTICALS = [
    { id: 'market', name: '市场 / 选品情报' },
    { id: 'competitor', name: '竞品与跟卖监控' },
    { id: 'sourcing', name: '货源与 1688 供应链' },
    { id: 'content', name: '商品内容与俄语本地化' },
    { id: 'compliance', name: '类目属性映射与合规认证' },
    { id: 'pricing', name: '定价与利润' },
    { id: 'promo', name: 'Ozon 促销活动与广告' },
    { id: 'inventory', name: '库存与补货' },
    { id: 'sla', name: 'rFBS 履约 SLA 与超时' },
    { id: 'logistics', name: '跨境物流 / 面单 / 轨迹 / 清关' },
    { id: 'cs', name: '俄语客服 / Q&A / 评价' },
    { id: 'returns', name: '退货 / 取消 / 索赔 / 争议' },
    { id: 'finance', name: '财务对账 / 结算 / 回款 / 汇兑' },
    { id: 'tax', name: '税务与资金合规' },
    { id: 'team', name: '多店多账号 / 团队权限 / 审计' },
    { id: 'bi', name: '数据 BI 与预警' },
    { id: 'health', name: '店铺健康度 / 评分 / 罚则' },
    { id: 'fulfillMode', name: 'FBO vs rFBS 决策与海外仓' },
    { id: 'brand', name: '品牌与内容资产' },
    { id: 'risk', name: '风控（封店 / 违规）' },
    { id: 'ai', name: 'AI Agent 编排 / 人在环 / 知识库 / 自然语言' },
    { id: 'integration', name: '平台接入与 API 变更治理' },
  ];

  // [id, vertical, title, pain, who, gap, solution, pri, status, view, agent, evidenceKeys, inferred]
  const RAW = [
    ['R01', 'market', '多维选品评分（权重公开、红线先过滤）', '爆款榜只看销量，认领后才发现毛利不够或带电/认证卡住', '老板/运营', 'ERP 偏采集上架，选品评分权重不透明；MPStats 偏外部数据不含 1688 成本', '选品雷达按毛利阈值认领；评分拆分销量/毛利/1688 匹配度，禁限售先拦截', 'P1', 'live', 'market', 'selection_radar', ['mpstats', 'mpVsMg'], false],
    ['R02', 'market', 'realFBS 改按类目固定佣金后重排 SKU', '2026-07-01 起 realFBS 取消价格分档，按类目固定费率，原利润表失效', '老板/运营', '多数表格仍按价格阶梯算佣金', '汇率佣金重算 Agent 已可批量重算毛利（当前按价格阶梯）；规划：利润模型新增「按类目固定费率」口径并给建议价', 'P0', 'live', 'compete', 'fx_commission', ['commJul', 'commJul2', 'commAug'], false],
    ['R03', 'market', '节点/季节需求预测（黑五、新年、开学季）', '备货与报名节奏靠经验，旺季断货或滞销', '老板/运营', '外部工具有季节性曲线，但不联动自家库存与采购周期', '规划：接入 MPStats 类季节曲线 + 自家销量，生成备货/报名日历', 'P2', 'live', 'market', '', ['mpstats'], true],
    ['R04', 'competitor', '我方商品卡跟卖监控', '同款卖家低价上架分流曝光，发现时订单已下滑', '运营', 'ERP 多为手动查看；无告警与应对建议', '选品页已有「跟卖监控」标签；规划：跟卖价格监控 Agent 告警跟卖者价格/评分/价差，应对建议进审批', 'P0', 'live', 'compete', '', ['followSell', 'priceIndex'], false],
    ['R05', 'competitor', '价格指数（绿/黄/红）监控 + 底价保护', '价格指数变红失去推广，盲目降价又击穿利润', '运营/老板', '工具只给指数，不结合成本底价', '利润定价已有跟卖价/活动价情景对比；规划：价格指数绿/黄/红分区 + 建议价=max(竞品价×阈值, 利润底价)', 'P0', 'live', 'compete', 'profit_guard', ['priceIndex', 'priceIndex2', 'dxmListing'], false],
    ['R06', 'competitor', '外部平台同款比价', '价格指数也会参考外部平台价格，卖家看不到来源', '运营', '无整合视图', '规划：接入外部比价数据源，标出拉低指数的外部链接', 'P2', 'partial', 'compete', '', ['priceIndex'], false],
    ['R07', 'sourcing', '1688 采购下单跟单与入库回写', '出单后人工去 1688 下单，PO 与订单对不上，超时', '运营/仓管', 'ERP 有采购模块但与 rFBS 时效不联动', '1688 采购跟单 Agent 消化待采购单并推进待发货；规划：接 1688 开放平台自动下单与 PO 回写', 'P1', 'live', 'orders', 'purchase_1688', ['open1688', 'dxmPlugin'], false],
    ['R08', 'sourcing', '以图搜货 / 断货换供', '供应商断货或涨价，临时找替代耗时', '运营', '需人工搜索', '规划：1688 图搜接口 + 价格/起订量对比，生成换供建议进审批', 'P2', 'partial', 'market', '', ['open1688'], false],
    ['R09', 'sourcing', '采购价变动触发利润重算', '1688 涨价未同步到定价，持续亏损', '老板/运营', '采购与定价两套表', '利润守门/汇率佣金重算 Agent 已覆盖汇率与佣金；采购价自动拉取待接 1688', 'P1', 'live', 'compete', 'profit_guard', ['open1688'], true],
    ['R10', 'content', '俄语标题公式评分与改写', '机翻标题语法差、堆词，搜索与转化差', '运营', 'ERP 有 AI 翻译，但缺少可解释的评分与公式校验', '刊登页已展示俄文标题与类目映射；规划：按「品牌+类型+型号+关键属性+规格」评分并给改写建议，确认后写回', 'P0', 'live', 'content', 'listing_publish', ['dxmTitle', 'contentRating', 'miaoshouAi'], false],
    ['R11', 'content', '内容评分补齐清单（属性/媒体/富文本）', '内容评分低影响曝光，不知道先补什么', '运营', '后台只给分数', '规划：按搜索属性/媒体/富文本/附加属性四块拆解内容评分缺口，生成补齐任务', 'P0', 'live', 'content', '', ['contentRating', 'attrs'], false],
    ['R12', 'content', '图片规范与 AI 生图合规', '主图带文字水印、比例不对被降权；AI 图与实物不符引发差评', '运营/美工', '生图工具不做合规校验', '规划：校验图片数量/主图规范；AI 生图需与实物一致，作为待确认项', 'P1', 'partial', 'content', '', ['imgSpec', 'aiImg', 'aiImgOzon'], false],
    ['R13', 'content', '视频与富文本内容生成', '富文本/视频占内容分但制作成本高', '运营/美工', '多数 ERP 未覆盖 Ozon 富文本 JSON', '规划：模板化生成 Rich-контент JSON + 短视频脚本', 'P2', 'partial', 'content', '', ['contentRating', 'miaoshouAi'], false],
    ['R14', 'content', '高频 Q&A 回写商品卡', '同一问题反复被问，客服成本高', '客服/运营', '问答与内容割裂', '规划：问答聚类后生成描述补丁，进审批后写回', 'P2', 'live', 'content', '', ['reviewApi'], true],
    ['R15', 'compliance', '类目/属性映射（description-category）', '类目选错或必填属性缺失导致审核失败', '运营', 'ERP 有映射但缺失原因不透明', '刊登页已展示类目映射完整度；规划：适配层接 /v1/description-category/attribute 拉取必填属性', 'P1', 'live', 'content', 'listing_publish', ['coreApi', 'importHabr'], false],
    ['R16', 'compliance', 'EAC 证书 / 豁免函管理与到期预警', '证书型号与卡片不一致或过期，被下架或拒收', '运营/老板', '证书散落在邮件与网盘', '规划：合规检查 Agent 按品类判定需 EAC CoC/DoC 或豁免函，记录证书号与到期日并预警', 'P0', 'live', 'content', '', ['eac', 'prohibited'], false],
    ['R17', 'compliance', 'Честный знак 标签品类识别', '鞋服/香水/儿童用品等需 Data Matrix，漏贴被拒收', '运营/仓管', '无自动识别', '规划：合规检查对必贴 Data Matrix 品类标红并生成待办', 'P1', 'live', 'content', '', ['marking'], false],
    ['R18', 'compliance', '禁限售词与品类拦截', '电子烟、无人机、芯片等禁售品误上架致违规', '运营', '靠人工记忆', '工作台合规提示条已列禁售品类；规划：按关键词/类目自动拦截，命中则阻止发布并进审批', 'P0', 'live', 'content', '', ['prohibited'], false],
    ['R19', 'compliance', '商品卡合并违规检测', '2026-04-15 起禁止不同型号/品牌合并，反复违规每次 1000₽', '运营', '无检测', '规划：店铺健康页统计合并违规数，刊登页提示拆分', 'P1', 'live', 'health', '', ['cardMerge', 'apr2026'], false],
    ['R20', 'pricing', '可配置成本栈与净利口径', '只看 GMV，佣金/头程/手续费/退货/广告没算全', '老板/财务', '黑盒公式', '利润定价共享费率（汇率/运费/佣金阶梯）可编辑；规划：成本栈加入广告/退货/罚金，并区分预估与结算', 'P0', 'live', 'compete', 'profit_guard', ['dxmProfit'], false],
    ['R21', 'pricing', '汇率与佣金变动自动重算 + 建议价', '汇率波动吞噬利润，调价滞后', '老板/运营', '手工周期性重算', '汇率佣金重算 + 利润守门 Agent 标记偏低 SKU 并给建议价', 'P0', 'live', 'profit', 'fx_commission', ['currency', 'commJul'], false],
    ['R22', 'pricing', '利润底价贯穿促销/跟卖/调价', '平台自动打折或报名活动击穿成本', '老板', 'ERP 有最低价字段，但不联动活动模拟', '利润守门 Agent 标记低毛利 SKU，利润定价含活动价情景；规划：底价（目标毛利反推）统一贯穿促销/跟卖/调价', 'P0', 'live', 'compete', 'profit_guard', ['dxmListing'], false],
    ['R23', 'pricing', '跨境 VAT 草案压力测试', 'Minfin 已提交法案：跨境电商进口 VAT 拟 2027 年 7%、2028 年 14%、2029 年起 22%（未生效），低毛利 SKU 将亏损', '老板/财务', '无情景测算', '规划：利润定价新增 VAT 7%/14%/22% 三档情景测算（未生效，仅测算）', 'P1', 'live', 'compete', '', ['vat1', 'vat2', 'vat3'], false],
    ['R24', 'promo', '活动报名前利润模拟', '报名后才发现活动价亏损', '运营/老板', '后台只给候选商品和建议价', '利润定价已有活动价情景；规划：接 /v1/actions 候选商品按 action_price 逐 SKU 测算净利，促销守门 Agent 只把达标 SKU 送审批', 'P0', 'live', 'promo', 'profit_guard', ['actionsApi'], false],
    ['R25', 'promo', '广告 ДРР / ROI 监控与亏损暂停', 'Трафареты/Оплата за заказ 花费高但净利为负', '运营/老板', 'Performance API 对 CPC 无 SKU 级明细，需自建归因', '规划：广告表按 ДРР=花费/广告销售额 与广告后净利告警；暂停建议进审批', 'P0', 'live', 'promo', '', ['perf1', 'perf2', 'perfDocs'], false],
    ['R26', 'promo', '按利润分配广告预算', '预算平均撒，高毛利 SKU 投放不足', '老板', '无利润口径预算', '规划：按 SKU 广告后净利排序推荐预算', 'P2', 'live', 'promo', '', ['perf2'], true],
    ['R27', 'inventory', '安全库存补货与库存同步', '超卖或断货', '仓管/运营', '规则分散', '库存补货 Agent + 库存同步规则', 'P1', 'live', 'logistics', 'inventory_restock', ['coreApi'], false],
    ['R28', 'inventory', '多店共享库存防超卖', '同货多店同时卖，库存未分摊', '仓管', '需要人工分配', '规划：主仓库存按店铺比例分配并实时回写 /v2/products/stocks', 'P1', 'live', 'supply', '', ['coreApi'], true],
    ['R29', 'sla', '备货截止倒计时与超时抢救', '逾期发货率 ≥20% 可能封仓 3 天', '仓管/运营', 'ERP 有倒计时但无自动抢救', '超时抢救 Agent 按 eta 排序审单→面单→发货，缺货转采购', 'P0', 'live', 'orders', 'timeout_rescue', ['lateShip', 'qualityCif'], false],
    ['R30', 'sla', '仓库休息日对截单期影响', '休息日设置错误导致整批超时', '仓管', '无提示', '规划：读取仓库工作日配置，提示受影响订单', 'P1', 'live', 'sla', '', ['qualityCif'], false],
    ['R31', 'sla', 'rFBS 状态与运单号回传', '未及时回传 sent-by-seller/轨迹，按时交货率下降', '仓管', '部分 ERP 只做发货', '审单履约 Agent 在本地推进订单状态；规划：适配层接 /v2/fbs/posting/* 与 tracking-number/set 自动回传', 'P0', 'live', 'sla', 'order_fulfill', ['rfbsApi', 'onTime'], false],
    ['R32', 'logistics', '渠道规则匹配与运价比较', '带电/超重走错渠道被退回', '仓管', '规则静态', '自动化规则按重量匹配渠道；带电识别由合规检查补充', 'P1', 'live', 'sla', 'order_fulfill', ['logisticsChoose'], false],
    ['R33', 'logistics', '轨迹停滞/清关异常自动建单', '包裹卡关买家发起索赔', '客服/仓管', '人工巡检', '物流轨迹异常 Agent 自动预警并建索赔工单', 'P1', 'live', 'orders', 'logistics_anomaly', ['customs'], false],
    ['R34', 'logistics', '报关资料一致性校验', '品名/HS/俄文标签不一致被扣关', '仓管/运营', '无校验', '规划：发货前比对商品卡、证书与申报品名', 'P1', 'live', 'sla', '', ['customs', 'eac'], false],
    ['R35', 'cs', '俄语差评/问答回复（AI 草稿需确认）', '俄语沟通慢，差评不回影响评分', '客服', 'API 读取评价/问答需 Premium Plus', '俄语客服 Agent 按模板生成回复草稿；规划：接入评价/问答 API 时识别 Premium Plus 订阅门槛', 'P1', 'live', 'cs', 'ru_cs', ['reviewApi'], false],
    ['R36', 'cs', '多店买家聊天聚合收件箱', '多店来回切后台回消息', '客服', '店小秘有消息同步，缺 AI 草稿', '规划：/v3/chat/list 聚合 + AI 草稿 + 人工确认', 'P1', 'live', 'inbox', '', ['chatApi', 'dxmGuide'], false],
    ['R37', 'cs', '差评根因聚类回流选品/内容', '同类差评反复出现', '老板/运营', '无聚类', '差评预警升级 Agent 已升级高风险差评；规划：差评按质量/物流/描述不符聚类，推送给选品与内容 Agent', 'P2', 'live', 'inbox', 'review_escalate', ['reviewApi'], true],
    ['R38', 'returns', '退货/取消/索赔状态机', '工单散乱，超期自动判负', '客服', '状态不透明', '退货理赔 Agent 推进 调查→同意/拒绝→退款→关闭', 'P1', 'live', 'returns', 'return_claim', ['returnsPvz'], false],
    ['R39', 'returns', 'IML 退货仓处置决策', '未注册/未决策，仓储期结束商品被销毁', '仓管/老板', '无提醒', '规划：按货值与回程运费建议 再上架/退回中国/销毁', 'P1', 'live', 'sla', '', ['returnsIml'], false],
    ['R40', 'finance', '结算明细 vs 订单利润逐单对账', '佣金/物流多扣、退货扣款看不懂，回款对不上', '财务/老板', '对账靠导 Excel；旧 transaction API 已于 2026-09 停用', '规划：结算对账页逐单比对预估与结算（新 /v1/finance/accrual/* 接口），差异生成申诉草稿进审批', 'P0', 'live', 'finance', '', ['finApi', 'finApiHabr', 'dxmProfit'], false],
    ['R41', 'finance', '回款日历与资金预测', '不知道哪天到账，备货资金紧', '财务/老板', '无预测', '规划：按「月两次结算、人民币最低付款额」规则生成回款日历（规则为时点快照）', 'P1', 'live', 'finance', '', ['payout', 'payout2'], false],
    ['R42', 'finance', '汇兑损益（下单日 vs 结算汇率）', '卢布波动造成隐性亏损', '财务', '多数工具不拆分汇损', '规划：对账页单列下单日 vs 结算日汇兑差', 'P1', 'live', 'finance', '', ['currency'], false],
    ['R43', 'tax', '收款主体与资金合规', '钱包、对公提现、主体不一致导致冻结', '财务/老板', '无检查', '规划：店铺-主体-收款账户一致性检查', 'P2', 'live', 'finance', '', ['payout', 'storesLicense'], false],
    ['R44', 'team', '多店分区 + 角色权限（含财务角色）', '多人共用账号、越权操作', '老板', '权限粗', '多店分区 + 老板/运营/仓管/客服 四角色已上线；规划：新增「财务」角色与细粒度权限', 'P1', 'live', 'platform', '', ['dxmGuide'], false],
    ['R45', 'team', '操作审计日志', '改价/退款出问题找不到责任人', '老板', '缺少统一审计', '审批中心底部统一审计日志：Agent 运行、指令台执行、审批通过/驳回、退款与改价全部记录操作人/时间/对象/结果', 'P0', 'live', 'approvals', '', [], true],
    ['R46', 'team', '同主体多账号结构风险提示', '一照最多 6 店；同主体同品范围可能被停用', '老板', '无提示', '规划：健康页检测跨店重复 SKU 并提示', 'P1', 'live', 'health', '', ['storesLicense', 'banGuide'], false],
    ['R47', 'bi', '经营周报（销售/净利/超时/退货）', '老板看不到全局', '老板', '报表分散', '周报汇报 Agent 生成快照', 'P1', 'live', 'weekly', 'weekly_report', ['mpstatsCab'], false],
    ['R48', 'bi', '每日经营简报推送', '每天手工截图汇报', '老板', 'Ozon 已推每日汇总，但不含利润与 Agent 动作', '规划：日报推送到 IM/邮件（需授权）', 'P2', 'partial', 'platform', '', ['dailySummary'], false],
    ['R49', 'health', '服务质量指标看板', '取消率(14天,10%)、逾期发货(7天)、渠道错误(1%) 超标被限售', '老板/运营', '后台有但不预测', '工作台已有超时/待审/差评/退货待办提醒；规划：店铺健康页按取消率/逾期/渠道错误阈值分区 + 趋势', 'P0', 'live', 'health', '', ['qualityCn', 'lateShip', 'onTime'], false],
    ['R50', 'health', '错误指数分区与罚金估算', '2026-09-22 起错误指数重置，5.1–10% / >10% 分档罚款', '老板/财务', '无估算', '规划：按 2026-09-22 新分档（5.1–10% / >10%）估算罚金并提示抢救', 'P0', 'live', 'health', '', ['errIndex', 'errIndex2'], false],
    ['R51', 'fulfillMode', 'SKU 级履约模式决策（rFBS → FBP/FBO）', '爆款一直直发，时效慢、取消多', '老板', '无量化对比', '规划：物流页决策卡按日销、单件成本、资金占用给出 rFBS/FBO 建议（当前开店引导仅支持 rFBS）', 'P1', 'live', 'supply', '', ['fulfillChoose', 'fulfillCmp'], false],
    ['R52', 'fulfillMode', '海外仓补货计划与滞销清理', 'FBO 出库申请时限 60 天，滞销难处理', '老板/仓管', '无计划', '规划：按周转天数生成补货与清仓建议', 'P2', 'live', 'supply', '', ['commJul', 'apr2026'], false],
    ['R53', 'brand', '品牌/图片/文案资产库与防盗图', '图片被盗用、跟卖难区分', '运营/美工', '无资产库', '规划：资产库 + 相似图检测', 'P2', 'live', 'content', '', ['aiImg', 'followSell'], false],
    ['R54', 'risk', '封店/违规风险评分', '可疑活动风控、铺货店清退，资金冻结', '老板', '无预警', '规划：健康页综合指标给风险分；风险动作进审批', 'P1', 'live', 'health', '', ['suspicious', 'banGuide'], false],
    ['R55', 'ai', '自然语言指令台', '功能多、找不到入口；老板想一句话下指令', '全员', 'ERP 多为菜单式', 'AI 指令台：12 类意图（调价、超时、差评、补货、采购、审单、物流异常、周报、查询、切店、导航、跑全部 Agent）→ 预览影响范围 → 确认执行 / 高风险送审批；当前为本地规则解析，预留大模型接入', 'P0', 'live', 'copilot', '', ['mcp1'], true],
    ['R56', 'ai', '人在环审批队列', 'Agent 全自动改价/报名风险大', '老板/财务', '自动化工具多为一键全自动', '审批中心：改价 >10%、退款 ≥2000₽、采购 ≥¥1000、取消订单自动进队列，老板通过即执行、驳回留痕；报名活动/暂停广告/下架待接入', 'P0', 'live', 'approvals', '', [], true],
    ['R57', 'ai', 'Agent 编排一键级联 + 定时回合', '多个工具各跑各的', '老板/运营', '无编排', '13 个 Agent 一键级联 + 定时回合，结果写入同一业务对象（目标扩展至 19 个）', 'P0', 'live', 'agents', '', [], true],
    ['R58', 'ai', '平台规则知识库（规则变更→阈值更新）', 'Ozon 规则频繁变（佣金、罚则、API），人工跟不上', '老板/运营', '无结构化规则库', '规划：阈值以「来源+日期」结构化存放并在页面标注，RAG 检索规则文档', 'P1', 'live', 'platform', '', ['errIndex', 'commJul', 'finApi'], false],
    ['R59', 'ai', 'Agent 通过 MCP 调用 Ozon API', '大模型无法安全调用平台接口', '技术', '社区已有 Ozon MCP Server', '规划：适配层封装为工具，经审批后执行', 'P2', 'partial', 'platform', '', ['mcp1', 'mcp2'], false],
    ['R60', 'integration', 'Ozon Seller API 适配层', '离线工具无法落地真实店铺', '技术/老板', '—', 'js/adapters/ozon-seller-api.js：17 个业务动作映射到 Seller API 端点，能力矩阵可查看；当前离线模式运行，真实调用需后端代理 + Client-Id/Api-Key', 'P0', 'partial', 'platform', '', ['ozonDocs', 'coreApi', 'shipV4'], false],
    ['R61', 'integration', 'API 废弃/迁移监控', '2026-09-08 停用 /v3/finance/transaction/*，未迁移则利润算在旧数据上', '技术/财务', '无监控', '适配层已标注 /v3/finance/transaction/* 于 2026-09-08 停用并改用 /v1/finance/accrual/*；规划：定期比对官方变更日志自动告警', 'P1', 'partial', 'platform', '', ['finApi', 'finApiHabr', 'shipV4'], false],
    ['R62', 'integration', '订阅门槛识别（Premium Plus 等）', '评价/问答/聊天 API 需订阅，接入后报错', '技术', '无提示', '适配层已在评价/聊天端点标注订阅门槛；规划：接入后按报错码自动识别并提示升级', 'P2', 'partial', 'platform', '', ['reviewApi', 'chatApi'], false],
  ];

  const LIST = RAW.map(r => ({
    id: r[0], vertical: r[1], title: r[2], pain: r[3], who: r[4], gap: r[5], solution: r[6],
    priority: r[7], status: r[8], view: r[9], agent: r[10],
    evidence: r[11].map(k => EV[k]).filter(Boolean), inferred: r[12],
  }));

  const STATUS_LABEL = { live: '已上线', partial: '部分上线', planned: '规划' };

  return { VERTICALS, LIST, EV, STATUS_LABEL };
})();
if (typeof module !== 'undefined') module.exports = (typeof window !== 'undefined' ? window : globalThis).OzonFlowRequirements;
